name: Autocloser
on: 
  pull_request:
  workflow_dispatch: # 手动触发
  
jobs:
  autoclose:
    runs-on: ubuntu-latest
    if: github.repository == 'RayWangQvQ/BiliBiliTool.Docs'
    steps:
    - uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "This PR was automatically closed because it did not follow the PR template."
        pr-pattern: ".*：【yes】\\s*-->.*"
