name: bilibili-daily-task


on:
  
  push: # push触发
    branches: [ main ]
  workflow_dispatch: # 手动触发
# schedule: # 计划任务触发
  # - cron: '0 4 * * *'
    

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:
    
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
  
    # IP1
    - name: IP
      run: |
       sudo curl ifconfig.me
       
    # IP2
    - name: IP
      run: |
       curl http://httpbin.org/ip
      
    # .Net 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: 切换目录
      run: cd ./test
    
    # 安装依赖
    - name: Install dependencies
      run: |
        cd ./test
        dotnet restore
      
    # 构建应用
    - name: Build
      run: |
        cd ./test
        dotnet build --configuration Release --no-restore
       
    # 运行
    - name: Run
      env:
        Ray_BiliBiliCookie:UserId: ${{secrets.USERID}}
        Ray_BiliBiliCookie:SessData: ${{secrets.SESSDATA}}
        Ray_BiliBiliCookie:BiliJct: ${{secrets.BILIJCT}}
        Ray_Push:PushScKey: ${{secrets.PUSHSCKEY}}
        Ray_Security:IntervalSecondsBetweenRequestApi: ${{secrets.INTERVALSECONDSBETWEENREQUESTAPI}}
        Ray_Security:IntervalMethodTypes: ${{secrets.INTERVALMETHODTYPES}}
        Ray_DailyTaskConfig:NumberOfCoins: ${{secrets.NUMBEROFCOINS}}
        Ray_DailyTaskConfig:SelectLike: ${{secrets.SELECTLIKE}}
        Ray_DailyTaskConfig:SupportUpIds: ${{secrets.SUPPORTUPIDS}}
        Ray_DailyTaskConfig:DayOfAutoCharge: ${{secrets.DAYOFAUTOCHARGE}}
        Ray_DailyTaskConfig:DayOfReceiveVipPrivilege: ${{secrets.DAYOFRECEIVEVIPPRIVILEGE}}
        Ray_DailyTaskConfig:DevicePlatform: ${{secrets.DEVICEPLATFORM}}
        Ray_Serilog:WriteTo:0:Args:restrictedToMinimumLevel: ${{secrets.CONSOLELOGLEVEL}}
        Ray_Serilog:WriteTo:0:Args:outputTemplate: ${{secrets.CONSOLELOGTEMPLATE}}
      run: dotnet run -p ./test/src/Ray.BiliBiliTool.Console -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}}
